# Generated by Django 5.1 on 2025-11-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Entrenamiento_Canino', '0002_perro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id_entrenamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lugar', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='app_Entrenamiento_Canino.perro')),
            ],
        ),
    ]
